### ISSUE TITLE
Area distribution by species

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/SemiF-DataReporting#47]
get area distribution stats to tell us something about size classes for each species. 

Use the `cutout_props.bbox_area_cm2` and `category.common_name`

a single csv using `groupby` to show both `is_primary==True` and `is_primary==False` like:
```csv
species,is_primary,area_class,count
pigweed,true,small,100
pigweed,false,small,100
pigweed,true,medium,100
pigweed,falsemedium,100
```

Use this buckets or area classes: 
```yaml
area_categories:
    very_small: [0, 0.1]
    small: [0.1, 1]
    medium: [1, 10]
    medium_large: [10, 100]
    large: [100, 1000]
    very_large: [1000, 1000000]
```
